---
title: "Prerequisites"
description: "...things that need to be in place _before_ the R course."
author:
  - name: Søren O'Neill
    url: www.oneill.dk
date: today
output:
  distill::distill_article:
    self_contained: false
#collections:
#  posts:
#    disqus: reproducible-finance-with-r
#categories:
#  - English
#  - Installation
creative_commons: CC BY
format: html
editor: source
---

## Prerequisites

You'r going to need a computer ...

-   A *somewhat* modern computer
    -   Sufficient storage (+500 Mb) on your harddisk for the installation
    -   Sufficient memory (+1 Gb) - the more, the better
-   A *somehwat* modern operating system
    -   Linux (Ubuntu 18+, Debian 9+, OpenSuse 15+, Fedora 19+, Redhat 7+, etc)
    -   Windows 10+
    -   MacOS10.15+
-   A working internet connection

If you are in doubt _or_ your computer was issues by SDU, SLB, or OUH, please see below:

:::{.callout-note collapse=true}

## How to find the information about your computer

If you already have a working installation of R, you can use [this script](installation_check_en.qmd)  to list all the relevant information about your computer and its software.

::: panel-tabset
### Windows

[Windows 10](https://support.microsoft.com/en-us/windows/view-your-system-info-a965a8f2-0773-1d65-472a-1e747c9ebe00)

[Windows 10](https://youtu.be/5SXXGHKJ8I4)

### MacOS

[MacOS](https://support.apple.com/guide/mac-help/get-system-information-about-your-mac-syspr35536/mac)

### Linux

#### Debian based distributions

If you're running Linux, you probably know all this stuff already, down to the clock speed of your RAM and the block size of ext4, but if not:

Run the following in a terminal, to get information about your operating system (uname), your hardware (lscpu) and disk space (df):

```
$ uname -a
$ lscpu
$ df -h
```

#### Red Hat based distributions

Run the following in a terminal, to get information about your operating system (hostnamectl), your hardware (lscpu) and disk space (df):

```{} 
$ hostnamectl
$ lscpu
$ df -h

```

#### Gentoo, Arch, or similar?

You definitely do not need any assistance here...

:::

:::

::: {.callout-important  collapse="true"}
## Is you computer an older model?

If your computer is an older model, we recommend that you get someone to help you install R well in time _before_ the R-course.

Otherwise, you risk spending all your class time wrangling your computer instead of playing with R.

The R-ecosystem is constantly developing and new functionality is added all the time, which may be unavailable to you with an older R installation.

Your computer doesn't have to be brand spanking new, but if in doubt, contact the teachers _before_ the R course starts.

At the time of writing (summer 2022) we recommend you use R version4.x.x and RStudio version 2022.x.x

:::

::: {.callout-important  collapse="true"}
## Are you connected to an institutional network drive

Note, that if your computer is set up to use an institutional network drive (such as Microsoft OneDrive) as opposed to its local harddisk, it may slow things down somewhat ... it will still run, but slower due to the net-traffic overhead.

:::

::: {.callout-important  collapse="true"}
## Was your computer supplied by SDU?

Be aware that the local IT department on the Regional Hospitals and the Universiy may impose certain restrictions on your ability to install software on your computer:

-   Access to some webpages (e.g. CRAN) may be restricted, as may access to download some files from the internet.
-   Installation of software may require particular administrative rights which you do not have as standard.

If this is the case, it will impede and slow down your installation of R.

It is therefor a good idea, to get all of this sorted out _before_ the start of classes. Again, otherwise you risk spending all your class time wrangling your computer rather than playing with R.

...and we (the teacher) will gladly help you with the R-ecosystem, but not necessarily your computer or your operating system.

On an SDU issued computer, your best bet is to install software via the SDU IT Software Center.

:::

::: {.callout-important  collapse="true"}

## Was your computer supplied by SLB?

Be aware that the local IT department on the Regional Hospitals and the Universiy may impose certain restrictions on your ability to install software on your computer:

-   Access to some webpages (e.g. CRAN) may be restricted, as may access to download some files from the internet.
-   Installation of software may require particular administrative rights which you do not have as standard.

If this is the case, it will impede and slow down your installation of R.

It is therefor a good idea, to get all of this sorted out _before_ the start of classes. Again, otherwise you risk spending all your class time wrangling your computer rather than playing with R.

...and we (the teacher) will gladly help you with the R-ecosystem, but not necessarily your computer or your operating system.



:::

::: {.callout-important  collapse="true"}
## Was your computer supplied by OUH?

Some OUH employees in the past, have been advised to use a server-based R/RStudio solution, in place of a local installation on your computer -- that does **not** work well. We highly recommend a local installation on your own hard drive.

Be aware that the local IT department on the Regional Hospitals and the University may impose certain restrictions on your ability to install software on your computer:

-   Access to some webpages (e.g. CRAN) may be restricted, as may access to download some files from the internet.
-   Installation of software may require particular administrative rights which you do not have as standard.

If this is the case, it will impede and slow down your installation of R.

It is therefor a good idea, to get all of this sorted out _before_ the start of classes. Again, otherwise you risk spending all your class time wrangling your computer rather than playing with R.

...and we (the teacher) will gladly help you with the R-ecosystem, but not necessarily your computer or your operating system.

:::

<script src="https://giscus.app/client.js"
        data-repo="sorenoneill/r4phd"
        data-repo-id="R_kgDOJ9etDQ"
        data-category="Announcements"
        data-category-id="DIC_kwDOJ9etDc4CYApF"
        data-mapping="pathname"
        data-strict="0"
        data-reactions-enabled="0"
        data-emit-metadata="0"
        data-input-position="bottom"
        data-theme="cobalt"
        data-lang="en"
        crossorigin="anonymous"
        async>
</script>