project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!presentations/"
    - "!qmd_rrr/main_v1_DrJekylls_comments.qmd"

website:
  title: "R4phd"
  search: 
    location: navbar
    type: overlay
  navbar:
    background: primary
    #left:
    #  - href: index.qmd
    #    text: Home
  page-navigation: true
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Installation"
        contents:
          - href: qmd_installation/installation_quick_preparation_en.qmd
            text: "Getting started"
          - qmd_installation/installation_prerequisites_en.qmd
          - qmd_installation/installation_ecosystem_en.qmd
          - qmd_installation/installation_background_en.qmd
          - qmd_installation/installation_r_en.qmd
          - qmd_installation/installation_rstudio_en.qmd
          - qmd_installation/installation_r_packages_en.qmd
          - qmd_installation/installation_cloud_en.qmd
          - qmd_installation/installation_check_en.qmd
      - section: "Getting to know RStudio"
        contents:
          - qmd_gui/rstudio_introduction_to_gui_1_en.qmd
          - qmd_gui/rstudio_introduction_to_gui_2_en.qmd
          - qmd_gui/rstudio_introduction_to_gui_console_en.qmd
      - section: "Data structure"
        contents:
          - qmd_data_structure/tidy_data_en.qmd
      - section: "Manuscript workflow"
        contents:
          - qmd_manuscript_workflow/load_data_en.qmd
          - qmd_manuscript_workflow/inspect_data_en.qmd
          - qmd_manuscript_workflow/wrangle_data_en.qmd
      - section: "R course exercises"
        contents: 
        - section: "Day 1"
          contents: 
            - day_1_basics_of_Rstudio.qmd
            - day_1_basics_of_R_code.qmd
            - day_1_settting_up_your_course_project.qmd
            - day_1_quarto_documents.qmd
            - day_1_dplyr.qmd
            - day_1_other.qmd
        - section: "Day 2"
          contents:
            - day_2_ggplot2_basics.qmd
            - day_2_ggplot2_extras.qmd
        - section: "Day 3"
          contents:
            - day_3_factors.qmd
            - day_3_data_import.qmd
            - day_3_missings.qmd
            - day_3_tables.qmd
        - section: "Day 4"
          contents: 
            - day_4_hypothesis.qmd
            - day_4_regression.qmd
        - section: "RRR"
          contents:
            - qmd_rrr/reproducible_research_basics_exercises_en.qmd
            - qmd_rrr/reproducible_research_intro_en.qmd
            - qmd_rrr/reproducible_research_workflow_1_en.qmd
            - qmd_rrr/reproducible_research_basics_comments_how_en.qmd
            - qmd_rrr/reproducible_research_basics_comments_where_en.qmd
            - qmd_rrr/reproducible_research_basics_comments_what_en.qmd
            - qmd_rrr/reproducible_research_basics_white_space_en.qmd
            - qmd_rrr/reproducible_research_basics_readme_en.qmd
            - qmd_rrr/reproducible_research_basics_naming_stuff_en.qmd
            - qmd_rrr/reproducible_research_basics_file_structure_en.qmd
            - qmd_rrr/reproducible_research_workflow_2_en.qmd
            - qmd_rrr/reproducible_research_citations_en.qmd
            - qmd_rrr/reproducible_research_collaboration_en.qmd
      - section: "Base R"
        contents:
          - qmd_base_r/base_r_data_types_en.qmd
          - qmd_base_r/base_r_missing_data_en.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
toc: true
number-sections: true
# bibliography: references.bib  

comments:
  giscus:
    repo: sorenoneill/r4phd