project:
  type: website
  output-dir: docs

website:
  title: "R4phd"
  search: 
    location: navbar
    type: overlay
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
  page-navigation: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Dansk"
        contents:
          - section: "Installation"
            contents:
              - installation_prerequisites_da.qmd
              - installation_ecosystem_da.qmd
              - installation_background_da.qmd
              - installation_r_da.qmd
              - installation_rstudio.qmd
              - installation_r_pakker.qmd
              - installation_cloud.qmd
          - section: "Lær RStudio at kende"
            contents:
              - rstudio_introduktion_brugerflade_1.qmd
      - section: "English"
        contents:
          - section: "Installation"
            contents:
              - installation_prerequisites_en.qmd
              - installation_ecosystem_en.qmd
              - installation_background_en.qmd
          - section: "Getting to know RStudio"
            contents:
              - rstudio_introduktion_brugerflade_1.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
toc: true
number-sections: true
# bibliography: references.bib  

comments:
  giscus:
    repo: sorenoneill/r4phd