project:
  type: website
  output-dir: docs

website:
  title: "R4phd"
  search: 
    location: navbar
    type: overlay
  navbar:
    background: primary
    #left:
    #  - href: index.qmd
    #    text: Home
  page-navigation: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Installation"
        contents: 
          - section: "Dansk"
            contents:
              - section: "Installation"
                contents:
                  - href: installation_quick_preparation_da.qmd
                    text: "Kom i gang"
                  - href: installation_prerequisites_da.qmd
                    text: "Forudsætninger"
                  - installation_ecosystem_da.qmd
                  - installation_background_da.qmd
                  - installation_r_da.qmd
                  - installation_rstudio_da.qmd
                  - href: installation_r_pakker_da.qmd
                    text: "Installation af pakker"
                  - installation_cloud_da.qmd
              - section: "Lær RStudio at kende"
                contents:
                  - rstudio_introduction_to_gui_1_da.qmd
          - section: "English"
            contents:
              - section: "Installation"
                contents:
                  - href: installation_quick_preparation_en.qmd
                    text: "Getting started"
                  - installation_prerequisites_en.qmd
                  - installation_ecosystem_en.qmd
                  - installation_background_en.qmd
                  - installation_r_en.qmd
                  - installation_rstudio_en.qmd
                  - installation_r_packages_en.qmd
                  - installation_cloud_en.qmd
              - section: "Getting to know RStudio"
                contents:
                  - rstudio_introduction_to_gui_1_en.qmd
      - section: "R course exercises"
        contents: 
          - section: "Day 1"
            contents: 
              - day_1_basics_of_Rstudio.qmd
              - day_1_basics_of_R_code.qmd
              - day_1_settting_up_your_course_project.qmd
              - day_1_quarto_documents.qmd
              - day_1_dplyr.qmd
              - day_1_other.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
toc: true
number-sections: true
# bibliography: references.bib  

comments:
  giscus:
    repo: sorenoneill/r4phd