---
title: "Installation af R"
description: |
  Sådan installerer du R på din computer.
author:
  - name: Søren O'Neill
    url: www.oneill.dk
date: '`r Sys.Date()`'
output:
  distill::distill_article:
    self_contained: false
#collections:
#  posts:
#    disqus: reproducible-finance-with-r
#categories:
#  - Installation
creative_commons: CC BY
format: html
editor: source
---


## Installation

::: panel-tabset

## SDU

Hvis din computer er udleveret af SDU IT kan R kan installeres via SDUs _Software Center_.

**LINK?**

## Windows

R kan hentes på internettet fra dette link til [CRAN](https://cran.r-project.org/):

-   Nær toppen finder du linket **Download R for Windows**.
-   Klik på linket og download filen.
-   Når filen er hentet ned installeres på vanlig vis.

## MacOS

R kan hentes på internettet fra dette link til [CRAN](https://cran.r-project.org/):

-   Nær toppen finder du linket **Download R for macOS**.
-   Klik på linket og download filen.
-   Når filen er hentet ned installeres på vanlig vis.

## Linux

R er med al sandsynlighed en del af din foretrukne Linux distributions standard software repositorie. Bruger du en Debian baseret distribution, vil det derfor formentligt være så simpelt som:

```{bash}
#| echo: true
#| eval: false

user@linux$ sudo apt install r-base

```

Derforuden kan du med fordel installere følgende andre pakker hvis du vil bruge R til at generere litteratur referencer (pandoc) og/eller PDF filer (texlive) som output.

```{bash}
#| echo: true
#| eval: false

user@linux$ sudo apt install pandoc pandoc-citeproc texlive-base texlive-extra-utils texlive-font-utils texlive-fonts-recommended texlive-fonts-extra texlive-latex-base texlive-latex-extra texlive-latex-recommended texlive-pictures texlive-pstricks texlive-xetex lmodern texlive-lang-european g++ libxml2-dev libcurl4-openssl-dev libssl-dev 

```

Bruger du en anden distribution, som ikke er baseret på Debian (f.eks Arch eller Fedora) skal du installere tilsvarende pakker fra deres repositorier med deres pakke håndterings funktioner (yum, rpm, etc)
:::

## Tjek at R er installeret og fungerer

Hvis installationsprocessen forløb som forventet burde du nu have R installeret på din computer -- før vi går videre til at installere RStudio, er det en god ide lige at kontrollere at du nu også har et fungerende R udviklingsmiljø på plads:

::: panel-tabset

## Windows

For at tjekke om R er installeret skal du først åbne *Terminal* programmet på din Windows computer:

Åben *Run window* dialogen ved at trykke på tasterne *Windows + R*, i 'Åben' feltet i 'Kør' vinduet taster du *wt* (for Windows Terminal) og klikker på *OK*.

I *Windows Terminal* indtaster du nu:

```{bash}
#| echo: true
#| eval: false

...SKAF BILLEDE FRA EN WINDOWS
```

## MacOS

For at tjekke om R er installeret skal du først åbne *Terminal* programmet på din Mac computer:

*Terminal* kan findes i *Utilities* under *Applications* eller du kan trykke *Command-space* for at åbne *Spotlight* og indtaste "Terminal" og derpå dobbelt klikke på søge resultatet.

I MacOS *Terminalen* indtaster du nu:

```{bash}
#| echo: true
#| eval: false

...SKAF BILLEDE FRA EN MAC
```

## Linux

Åbn dit favorit *command-line interface* og afprøve følgende:

```{bash}
#| echo: true
#| eval: false

user@linux: R
```

Dit output skulle gerne være noget i stil med:

```{r}
#| echo: true
#| eval: false

R version 4.1.2 (2021-11-01) -- "Bird Hippie"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.
```
:::
