---
title: "Indlæs data fra RDS"
author:
  - name: Søren O'Neill
    url: www.oneill.dk
date: "2023-12-19"
#output:
#  distill::distill_article:
#    self_contained: false
#collections:
#  posts:
#    disqus: reproducible-finance-with-r
categories:
  - RStudio
  - Input
creative_commons: CC BY
format: html
editor: source
number-sections: true
---

## RDS

* RDS er en forkortelse af _R Data Serialization_ -- det betyder at alle data, også data som er sammensatte og asymmetriske i struktur, som f.eks en liste af lister af varierende længder, kan serialiseres og gemmes nemt.
* RDS er _ikke_ et simplet tekst format -- det er (eventuelt) et komprimmeret fil format som ikke er velegnet for en menneskelig læser
* RDS er derimod en simpel og effektiv måde at gemme og gen-indlæse data som allerede eksisterer i R hukommelsen.

## Tidyverse løsning

* Tidyverse inkluderer pakken [readr](https://readr.tidyverse.org/reference/read_rds.html) som indeholder et antal funktioner til læse og skrive til RDS filer. 

::: {.callout-tip collapse="true" title="Om RDA og RDATA formater.."}
Du kan ske at støde på formaterne .Rda og .RData -- de er stadig brugbare, men formentligt ikke velegnede til Reproducible Research. Vi anbefaler at bruge .Rds formater i stedet.
:::



<script src="https://giscus.app/client.js"
        data-repo="sorenoneill/r4phd"
        data-repo-id="R_kgDOJ9etDQ"
        data-category="Announcements"
        data-category-id="DIC_kwDOJ9etDc4CYApF"
        data-mapping="pathname"
        data-strict="0"
        data-reactions-enabled="0"
        data-emit-metadata="0"
        data-input-position="bottom"
        data-theme="cobalt"
        data-lang="en"
        crossorigin="anonymous"
        async>
</script>